// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/11/2026, 1:46:26 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/lianglaiyang_1/workspace/xinguan_wudong/code/tourist-pc-frontend/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/lianglaiyang_1/workspace/xinguan_wudong/code/tourist-pc-frontend/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/lianglaiyang_1/workspace/xinguan_wudong/code/tourist-pc-frontend/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/lianglaiyang_1/workspace/xinguan_wudong/code/tourist-pc-frontend/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/lianglaiyang_1/workspace/xinguan_wudong/code/tourist-pc-frontend/plugins/**/*.{js,ts,mjs}","/Users/lianglaiyang_1/workspace/xinguan_wudong/code/tourist-pc-frontend/composables/**/*.{js,ts,mjs}","/Users/lianglaiyang_1/workspace/xinguan_wudong/code/tourist-pc-frontend/utils/**/*.{js,ts,mjs}","/Users/lianglaiyang_1/workspace/xinguan_wudong/code/tourist-pc-frontend/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/lianglaiyang_1/workspace/xinguan_wudong/code/tourist-pc-frontend/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/lianglaiyang_1/workspace/xinguan_wudong/code/tourist-pc-frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;